### ISSUE TITLE
studentActivityType/studentActivityLevel has an incomplete definition

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#10]
I realize this is a very minor issue since we have spotty inclusion of definitions throughout the spec, but this element's definition ends with "(e.g.,".  Since StudentActivity is new and people will probably be looking at it, it may be wise to complete the sentence.

**Comment by vinceparedes** [comment]
Here is the full definition: A description of the separation of level in the activity (e.g., Varsity, Junior Varsity, Honors).  

A better version would be:  A description of the level of the activity (e.g., Varsity, Junior Varsity, Honors).  

Who should make this change?

**Comment by 4pins** [comment]
@vinceparedes will handle.

**Comment by vinceparedes** [comment]
changed, committed, pushed and will eventually be pulled.
