### ISSUE TITLE
StudentAttendanceSummary is it too manditory?

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#100]
MA only uses about half the mandatory data elements!

**Comment by vinceparedes** [comment]
Yes, I agree. This is the old SIF approach of narrow use cases. 

I think we should at least make the resident and below elements optional. Any other suggestions for optional elements?

**Comment by mattharris5** [comment]
Are you referring to the `xSre`? All of the elements are optional in that object. If you're using this elsewhere in the data model, maybe you could use the xPress `xAttendanceSummaryType` as a starting point?

**Comment by 4pins** [comment]
@NathanClinton No, the "new" object.  Which is built specifically to: function well within the enterprise, aid in migration, and allow for flexibility of codes.

http://specification.sifassociation.org/Implementation/NA/3.4/Collections/studentAttendanceSummarys.xhtml

@vinceparedes Here are the mandatory elements MA doesn't use, seems we need to relax this a lot.

StartDay, EndDay, Resident, and ExcusedAbsences

Go to town!

**Comment by 4pins** [comment]
I will address as I align with xSRE.

**Comment by 4pins** [comment]
Better now, I will upload soon.
