### ISSUE TITLE
LongTermSubstitute in staffSectionAssociations.

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#101]
MA uses a LongTermSubstitute flag.

Is this a long term substitute teaching assignment?  (Yes or No)

**Comment by vinceparedes** [comment]
Ideally this would go in the roleList. Or, it could be an MA extension.

**Comment by leslie8751** [comment]
Just fyi, Wyoming wouldn't use this.

**Comment by 4pins** [comment]
Good call on adding it to the role list, I'll send to Glenn King once we have him in the system.

**Comment by vinceparedes** [comment]
Since there is no SIF sanctioned codeset for roleList I am going to close this issue with a recommendation that a note for this be sent to MA. We could also create a codeset for SIF if the Tech Board is willing.
