### ISSUE TITLE
Employment Record might be an entity rather than a report. 

### ISSUE THREAD

**Issue by vinceparedes** [Access4Learning/NADM#103]
The word record in the title threw me off. I think all/most of these elements appear nowhere else in the spec which argues for it to be an entity object. 

It also needs a better name. The only thing worse would be Employment Info.

**Comment by 4pins** [comment]
I am fine with these changes.  What should we call it?

**Comment by 4pins** [comment]
employmentStatus?

**Comment by vinceparedes** [comment]
I think employment record is the best we can do.

**Comment by vinceparedes** [comment]
will close when done.
