### ISSUE TITLE
xSubtestScoreMetricType has the wrong code for `AgeScore`

### ISSUE THREAD

**Issue by mattharris5** [Access4Learning/NADM#105]
Looks like this was a typo in the enumeration. `Age Score` should have a value of `00490` according to CEDS but it is erroneously listed with a value of `00494`.

**Comment by mattharris5** [comment]
FYI @NathanClinton and @4pins - I fixed this directly on `master` because it was a very simple fix. See 244461b357376ffd505b0e502fd16f7427df9bac

**Comment by 4pins** [comment]
@mattharris5 Thanks, it will make it into the community review version.
