### ISSUE TITLE
Use explicit names for counts in StudentAttendanceSummary

### ISSUE THREAD

**Issue by mattharris5** [Access4Learning/NADM#110]
The community review 3.4 model has `daysAbsent` and `daysTardy` but then `excusedAbsences` and `unexcusedAbsences`. It's ambiguous whether we are referring to excused days or excused periods, so we should use an explicit and consistent name pattern for these fields.

**Comment by vinceparedes** [comment]
I think we can always improve on the names of elements. There are a lot of people who are concerned with backward compatibility, even from 2.7 to 3. This object is currently a copy from 2.7 moved to 3. The description of the object does make clear that the summary is with respect to daily attendance and not period attendance. 

On the other hand, this object is new for 3.4 and if we are going to make changes, now is the time. Also, there are way too many elements that are required. This is a holdover from when we designed to very narrow use cases.

**Comment by mattharris5** [comment]
It came up on the @Access4Learning/natb call today and I offered to submit the issue. It would probably be OK if the elements remained unchanged, but as you point out it's a good time to make the element names align semantically.
