### ISSUE TITLE
New Objects are in Separate Files

### ISSUE THREAD

**Issue by vinceparedes** [Access4Learning/NADM#116]
As I added new objects to 3.4 I kept them in separate files for easier location, editing, and review. 

In the entity and report folders, objects are in a single file. In the composite folder, I think they are mostly in separate files or cluster in a file because of the various types. 

It would probably be better to continue the practice of entity objects in a single file rather than a hybrid. 

@4pins  what do you think?

**Comment by 4pins** [comment]
Got for it!  Trying not to break anything.  :)
