### ISSUE TITLE
Subordinate elements have refId but should not

### ISSUE THREAD

**Issue by tqwhite** [Access4Learning/NADM#128]
Subordinate elements (e.g., iepEligabilityBackgroundType)  were extended from gOtherSIFType to allow extension. This brought along a refId as well as the extension point.

Since the subordinate elements are not exposed as independent objects the presence of a refId is inappropriate.

**Comment by tqwhite** [comment]
I think we should create a new global type, gSIF_ExtensibleType, that supplies an extension point but has no refId.

**Comment by aemnathanclinton** [comment]
We didn't extend from any SIF base type with similar xSre types.  xAttendanceEventType for instance is just an xs:complexType.  Here's an exerpt from SIFNAxSRECommonTypes.xsd
`
	<xs:complexType name="xAttendanceEventType">
		<xs:sequence>
			<xs:element name="school" type="xSchoolType" minOccurs="0"/>
			<xs:element name="calendarEventDate" type="xs:date" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<elementName>Calendar Event Date</elementName>
						<sifChar>O</sifChar>
						<cedsId>001275</cedsId>
						<cedsURL>https://ceds.ed.gov/cedselementdetails.aspx?termid=6241</cedsURL>
					</xs:appinfo>
					<xs:documentation>The date of the scheduled or unscheduled event.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attendanceStatus" type="xAttendanceStatusType" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<sifChar>O</sifChar>
						<cedsId>000076</cedsId>
						<cedsURL>https://ceds.ed.gov/cedselementdetails.aspx?termid=3076</cedsURL>
					</xs:appinfo>
					<xs:documentation>The status of a student's attendance during a given day while school is in session.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attendanceEventType" type="xAttendanceEventTypeType" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<sifChar>O</sifChar>
						<cedsId>000601</cedsId>
						<cedsURL>https://ceds.ed.gov/cedselementdetails.aspx?termid=3594</cedsURL>
					</xs:appinfo>
					<xs:documentation>The type of attendance event.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="absentAttendanceCategory" type="xAbsentAttendanceCategoryType" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<sifChar>O</sifChar>
						<cedsId>000599</cedsId>
						<cedsURL>https://ceds.ed.gov/cedselementdetails.aspx?termid=3592</cedsURL>
					</xs:appinfo>
					<xs:documentation>The category that describes how the student spends his or her time not physically present on school grounds and not participating in instruction or instruction-related activities at an approved off-grounds location.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="presentAttendanceCategory" type="xPresentAttendanceCategoryType" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<sifChar>O</sifChar>
						<cedsId>000600</cedsId>
						<cedsURL>https://ceds.ed.gov/cedselementdetails.aspx?termid=3593</cedsURL>
					</xs:appinfo>
					<xs:documentation>The category that describes how the student spends his or her time when attending an instructional program approved by the state and/or school.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attendanceValue" type="xs:decimal" minOccurs="0">
				<xs:annotation>
					<xs:documentation>A percentage representing the amount of time for this event. For example, if the student was in attendance for half of the day, this value would be 0.5.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timeTablePeriod" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:appinfo>
						<sifChar>O</sifChar>
						<cedsId>000522</cedsId>
						<cedsURL>https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=24024</cedsURL>
					</xs:appinfo>
					<xs:documentation>An indication of the portion of a typical daily session in which students receive instruction in a specified subject (e.g., morning, sixth period, block period, or AB schedules).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
`

**Comment by 4pins** [comment]
I seem to remember long conversations about having a "relaxed" version, where the refId is optional.  There is a reference to a "xStudentRelaxedType" in the StudentLocatorResponse.xsd but I cannot find where it is defined.

**Comment by 4pins** [comment]
While I didn't find the definition is does resolve somehow.
See:  http://specification.sifassociation.org/Implementation/NA/3.5/Collections/studentLocatorResults.xhtml#/studentLocatorResults/studentLocatorResult/student/@refId
