### ISSUE TITLE
Capitalization consistency when acronyms are used

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#149]
Existing:  xSRE
New:  xTransferIep
Recommend:  xTransferIEP

**Comment by tqwhite** [comment]
Disgusting but I will submit at my earliest convenience.

**Comment by tqwhite** [comment]
I'm confused. It _is_ xTransferIEP.

![screen shot 2017-11-21 at 2 19 47 pm](https://user-images.githubusercontent.com/28464/33094823-0e6458c4-cec7-11e7-989e-cccabbaf5542.png)

**Comment by 4pins** [comment]
Look at the last line (the collection definition).  in my mind that one should be consistent with the object, xTransferIEPs.  Similarly I think consistency would be good between the types and element definitions, but that is largely invisible.

**Comment by tqwhite** [comment]
I have renamed all types and files with 'IEP' to camel case, e.g., 'blahIep'
