### ISSUE TITLE
Spreadsheet for xPress definitions varies from the XSD

### ISSUE THREAD

**Issue by vinceparedes** [Access4Learning/NADM#15]
Jason, there were some discrepancies, especially in xRoster between the XSD I started with and the spreadsheet you gave me for the CEDS Ids and definitions.

**Comment by jwrage** [comment]
Can you be more specific?

**Comment by jwrage** [comment]
Added loginId (already checked in). Will also do a diff against the copy of the XSD I had been maintaining locally.

**Comment by 4pins** [comment]
@vinceparedes will cordinate with @jwrage during the final review period.

**Comment by jwrage** [comment]
@vinceparedes would mind please resending the version of the spreadsheet that I originally sent you via email so that I can cross compare? I did run a diff, but there are so many changes that it was not useful in identifying changes via the XSD.

**Comment by jwrage** [comment]
The spreadsheet was created earlier in the development cycle and lacked some of the elements in the current version of the XSD. The XSDs supersede the spreadsheet. Not an issue.
