### ISSUE TITLE
General review of xSRE

### ISSUE THREAD

**Issue by jwrage** [Access4Learning/NADM#17]

**Comment by jwrage** [comment]
@mattharris5 @NathanClinton here is some feedback from an initial review:

# Potential style issues
- Capitalization of "SRE" in xSRE does not follow convention
- Capitalization of xSRE/reportingLEA does not follow convention
- Should annotation/appinfo/element name use the "technical element name" (i.e. no spaces) or should spaces be included with appropriate capitalization? The current style in SRE varies from Roster.
- Should there be definitions in sreAttendanceSummaryType for startDate, endDate?
- Is there value in maintaining certain objects/elements with a "sre" prefix versus an "x" prefix? Really doesn't matter to me but I noticed a mix during the review.
- competencies/compentency/learningStandardItemURL capitalization does not follow convention
- programs/lep/perkinsLEPStatus and title3LEPParticipationStatus do not follow capitalization convention

# Potential data issues
- Where does the controlled vocabulary for xDisciplinaryActionCodeType originate?

**Comment by jwrage** [comment]
Do you have a logical ERD for the SRE model? Would be nice to have something illustrative.

**Comment by NathanClinton** [comment]
We do have a really old xMind document we created many moons ago that might give you an idea of our original intent.  It's way out of date, though, especially with the migration to xStudent.  
![sre 3_0 model](https://cloud.githubusercontent.com/assets/8107270/7575158/956240de-f7e7-11e4-8474-f23917abd803.jpg)

**Comment by NathanClinton** [comment]
Thanks for the feedback, Jason!  I'll incorporate what I can and comment on everything else soon.

**Comment by NathanClinton** [comment]
> @jwrage: Should annotation/appinfo/element name use the "technical element name" (i.e. no spaces) or should be spaces be included with appropriate capitalization? The current style in SRE varies from Roster.

-- We pulled the element name directly from the "technical element name" from CEDS and stuffed it into the annotation <elementName> tag.  I looked through xRoster and didn't notice any <elementName> tags.  Where can I find an example in xRoster to compare?

**Comment by NathanClinton** [comment]
> @jwrage: Where does the controlled vocabulary for xDisciplinaryActionCodeType originate?

-- It comes from CEDS:  https://ceds.ed.gov/cedselementdetails.aspx?termid=3479
I'm assuming they pulled it from the NCES handbook based on the numerical code format.

**Comment by jwrage** [comment]
@NathanClinton the annotations are in master. Are you not seeing them there?
@vinceparedes @4pins should we be using the descriptive element names, or technical element names?

**Comment by NathanClinton** [comment]
Oops, my bad.  I was looking in the SRE branch, which Matt is currently working on detangling.

**Comment by mattharris5** [comment]
@NathanClinton and @jwrage you should have received the notice that we merged xPress and xSre into the master branch. Everything validates now... but there was a lot of hand editing to resolve conflicts. (The main issue was that the SRE team was working from our own copy of master before master ever existed, meaning that the merge couldn't trace back to the "real" master as an ancestor.) I am pretty confident I got all of our miscellaneous fixes and changes in there, but you should check (or spot-check) the master branch to make sure some of the little changes are in there as expected. Sorry I can't be more confident about this.

**Comment by mattharris5** [comment]
Current status of @jwrage's original points:

> Capitalization of "SRE" in xSRE does not follow convention
> :white_check_mark:  This is fixed in 8c8da3e962

## 

> Capitalization of xSRE/reportingLEA does not follow convention
> :white_check_mark: This is fixed in 8c8da3e962

## 

> Should annotation/appinfo/element name use the "technical element name" (i.e. no spaces) or should spaces be included with appropriate capitalization? The current style in SRE varies from Roster.
> :warning: This is unresolved. @NathanClinton what are your thoughts?

## 

> Should there be definitions in sreAttendanceSummaryType for startDate, endDate?
> :white_check_mark: This is fixed in 8c8da3e962

## 

> Is there value in maintaining certain objects/elements with a "sre" prefix versus an "x" prefix? Really doesn't matter to me but I noticed a mix during the review.
> :white_check_mark: We've removed all of the "sre" prefixes in favor of "x" prefix for everything in 8c8da3e962

## 

> competencies/compentency/learningStandardItemURL capitalization does not follow convention
> :white_check_mark: This is fixed in 8c8da3e962

## 

> programs/lep/perkinsLEPStatus and title3LEPParticipationStatus do not follow capitalization convention
> :white_check_mark: This is fixed in 8c8da3e962

## 

> Where does the controlled vocabulary for xDisciplinaryActionCodeType originate?
> :white_check_mark: This is resolved in 8c8da3e962

**Comment by NathanClinton** [comment]
@mattharris5 In regards to the technical element names, we're waiting for guidance from @vinceparedes  and @4pins (see @jwrage's post above).

**Comment by 4pins** [comment]
Other annotation/appinfo/elementName use spaces and capital letters.  Which makes sense, the goal is NOT to repeat the element name.
