### ISSUE TITLE
Add allergies to xSRE

### ISSUE THREAD

**Issue by mattharris5** [Access4Learning/NADM#2]

**Comment by jwrage** [comment]
I actually have a student health object prototyped if you'd like to review it. We decided to not include it in the initial bundle of xPress objects since it was unrelated to rostering.

**Comment by mattharris5** [comment]
Yes - would love to see it and align xSRE.health to it.

**Comment by jwrage** [comment]
Here is a prototype. I'll see if I can dig up XSDs. This was never updated to align to SIF 3 data model names; it's still expressed in CEDS terms. This is another object that uses the compound code style that includes human readable and codified components.

****\* k12StudentHealth *****
JS object:

``` javascript
{ refId: '8ed974d4-321a-4917-960c-aca738adf153',
  studentRefId: '2716fd55-b8a2-4f4b-b259-309d20abc132',
  medicalAlerts: [ { description: 'Diabetes', severity: 'Chronic' } ],
  allergies: 
   [ { allergyType: 'AllergyToAluminum_402306009',
       allergySeverity: 'Mild',
       allergyReactionDescription: 'Blisters' },
     { allergyType: 'AllergyToAppleJuice_418314004',
       allergySeverity: 'Mild',
       allergyReactionDescription: 'Upset stomach' } ],
  immunizations: 
   [ { immunizationType: 'HepatitisB', immunizationDate: '20131001' },
     { immunizationType: 'Meningococcal',
       immunizationDate: '20120510' } ],
  screenings: 
   [ { type: 'Hearing', status: 'Passed', date: '20140810' },
     { type: 'Vision', status: 'Passed', date: '20140810' } ] }
```

JSON object:

``` json
{"refId":"8ed974d4-321a-4917-960c-aca738adf153","studentRefId":"2716fd55-b8a2-4f4b-b259-309d20abc132","medicalAlerts":[{"description":"Diabetes","severity":"Chronic"}],"allergies":[{"allergyType":"AllergyToAluminum_402306009","allergySeverity":"Mild","allergyReactionDescription":"Blisters"},{"allergyType":"AllergyToAppleJuice_418314004","allergySeverity":"Mild","allergyReactionDescription":"Upset stomach"}],"immunizations":[{"immunizationType":"HepatitisB","immunizationDate":"20131001"},{"immunizationType":"Meningococcal","immunizationDate":"20120510"}],"screenings":[{"type":"Hearing","status":"Passed","date":"20140810"},{"type":"Vision","status":"Passed","date":"20140810"}]}
```

Flattened object:

``` javascript
{ refId: '8ed974d4-321a-4917-960c-aca738adf153',
  studentRefId: '2716fd55-b8a2-4f4b-b259-309d20abc132',
  'medicalAlerts[0].description': 'Diabetes',
  'medicalAlerts[0].severity': 'Chronic',
  'allergies[0].allergyType': 'AllergyToAluminum_402306009',
  'allergies[0].allergySeverity': 'Mild',
  'allergies[0].allergyReactionDescription': 'Blisters',
  'immunizations[0].immunizationType': 'HepatitisB',
  'immunizations[0].immunizationDate': '20131001',
  'screenings[0].type': 'Hearing',
  'screenings[0].status': 'Passed',
  'screenings[0].date': '20140810' }
```

**Comment by jwrage** [comment]
Top level XSD definition:
	<xs:complexType name="k12StudentHealthType">
		<xs:complexContent>
			<xs:extension base="gSIF_CompositeType">
				<xs:sequence>
					
					<xs:element name="studentRefId" type="gRefIdPointerType"/>
					<xs:element name="medicalAlerts" type="sMedicalAlertListType"/>
					<xs:element name="allergies" type="sAllergyListType"/>
					<xs:element name="immunizations" type="sImmunizationListType"/>
					<xs:element name="screenings" type="sHealthScreeningListType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

**Comment by mattharris5** [comment]
In xSRE we have a health sequence that includes immunizations and healthTests. Looks like we might want to change healthTests to "screenings" to match up for now, and then we can add medicalAlert and allergy later.

FYI @NathanClinton

**Comment by 4pins** [comment]
@mattharris5 Would you like to own this (for 3.5)?
