### ISSUE TITLE
Add countryOfBirth to sDemographicsType

### ISSUE THREAD

**Issue by mattharris5** [Access4Learning/NADM#21]
@jwrage This is an important element for users of SRE. Would you support adding it to sDemographicsType? The type is `gCountryType`. If you approve, I can add it to the XSD in our branch.

**Comment by jwrage** [comment]
Fine as an optional.

**Comment by mattharris5** [comment]
OK thanks.

**Comment by NathanClinton** [comment]
I'm in the spec now.  I'll add it.

**Comment by mattharris5** [comment]
Added in 12f8e6e and merged in #1
