### ISSUE TITLE
Rename the xPress types with an "x" prefix instead of "s"

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#23]

**Comment by jwrage** [comment]
"Should" = yes. Does anyone have time?

**Comment by NathanClinton** [comment]
Find/replace is our friend here.  I can probably work it in.

Sincerely,

Nathan Clinton
Enterprise Architect
Office of Superintendent of Public Instruction
(360) 725-4965

**Comment by NathanClinton** [comment]
Sorry about the full e-mail post.  Still learning GitHub's ins & outs.

**Comment by mattharris5** [comment]
No problem. I am going to rename the issue, re-open it, and assign it to you then.

**Comment by jwrage** [comment]
Thanks @NathanClinton

**Comment by jwrage** [comment]
Hi @NathanClinton can you clarify the scope of changes you made? Did you change all implementations AND references that used the "s" prefix to "x"? I'm just wondering what's going to happen when these are merged if there will be some clean up work to the references in the non-SRE objects.
