### ISSUE TITLE
xPress objects do not include ##other elements

### ISSUE THREAD

**Issue by mattharris5** [Access4Learning/NADM#24]
My understanding is that all SIF 3 objects should include an `##other` element at the end of the sequence. None of the xPress objects include that currently - should we add?

**Comment by jwrage** [comment]
Forgive my ignorance, but what is the purpose of ##other? What _is_ it structurally, and is it documented in any data modeling / object development guide? Is there a specific reason that it is needed based on SRE use cases? If it needs to be included, could it be incorporated into the base composite object @vinceparedes @4pins ?

**Comment by vinceparedes** [comment]
These are extension points. These allow users to extend the object with a different namespace and schema. 

Since xPress objects inherit from a SIF type they do have an extension point at the top. However, SIF objects are supposed to have extension points inside each complex element except for lists. We have not done this.

**Comment by mattharris5** [comment]
The purpose, rationale, goals, and architecture are described in the [Data Model v.3 User Guide](https://www.sifassociation.org/Specification/Documents/NA_3-1/NA_DataModel_v3_0_Guide.pdf), starting on page 5. I'm not sure how widely the feature is used, but it is a well-documented part of the 3.x data model. For SRE, we see great value in cases where a particular state or region has additional detail that don't belong in a nationwide spec. For example, Washington state tracks very detailed race and ethnicity codes that aren't captured in the basic demographics in xStudent or xSRE. When transmitting a record within our state, we want to include that extra detail but it isn't relevant to the rest of the country. The extension point allows us to include these additional elements. There are other use cases as well, certainly.

I think it's safe to say that this _must_ be included in xPress if we are to conform to our own data guidelines.

Then again, we already rebuffed the data guidelines by rejecting the "List" naming convention—something that is also included in the document referenced above. So... I guess we aren't _required_ to follow our own rules. YUCK!

**Comment by jwrage** [comment]
Thanks for the info. I have no problem adding it and will undertake this next.

**Comment by mattharris5** [comment]
Thanks @jwrage!

**Comment by mattharris5** [comment]
I am being told by @4pins that the data model guide is incorrect and the processContents attribute is supposed to be set to "strict" instead of "lax" per the guide. John is attempting to get clarity from @vinceparedes on this.

**Comment by 4pins** [comment]
Still being added to Roster objects.

**Comment by 4pins** [comment]
Will be added over the final review period.

**Comment by NathanClinton** [comment]
SRE objects are missing ##other in a few places.  I'm going to create a different issue for that change.  

_EDIT:_ False alarm.  I was confused by the Health element structure, which actually lead to issue #39 .

**Comment by jwrage** [comment]
@mattharris5 as I dig into this in more detail I am becoming troubled. I talked with @4pins a bit but intuition and common sense are taking me back to: what are the specific needs? 

The data model guide actually does not dictate the use of extension points:
"Not every single element in SIF should be extensible: patterns can be identified to restrict where extensions are allowed. Wherever we want to allow an extension within those patterns, we add the following in the specification"

Given the design goals behind xPress Roster, I'm leaning to including extension points only when we have a specific need for it. What do you think?

**Comment by mattharris5** [comment]
Agreed that it shouldn't be included everywhere by default but there are some places that seem like they might benefit from extension points. The problem with the "when we have a specific need for it" argument is that one of the main reasons to include extension points is to be there for the cases we _can't_ anticipate. In other words: if we had a specific need for an extension point, we wouldn't need an extension point. 

Looking at xStudent, I suggest that at least these elements would benefit from extension points:
- xDemographicsType - for example, if a district or school needs to track an additional data point
- xEnrollmentType - for example, if there are important items about a specific district's schedule system that needs to be tracked
- xAcademicSummaryType - for example, if a school needs to use some of the other metrics but doesn't want to implement a full xSRE.

I am curious to hear @NathanClinton's thoughts given your latest comment.

Perhaps this needs to be a conversation with more participants from the tech board.

**Comment by NathanClinton** [comment]
With the implementation of a strict vocabulary (which I'm very much in favor of) we trade the ability to send more complete data to gain the ability to better, more easily interoperate.  We need it both ways for SRE.  For instance, Washington State can't map very well (if at all) to most of the enumerations I created for the SRE spec (can/should we implement ##other on enumerations?).  In those cases, we need the ##other elements to provide the level of detail needed for a complete SRE implementation within the state.  On the flip side, if we ever develop an interstate SRE, we will map what we can to the enumerations and exclude ##other elements only used in WA.  The same thing applies to elements other than enumerations--elements that only WA needs to send a complete record within the state, but that would not be used when sending records across state borders.  

I'm in favor of implementing ##other everywhere.

**Comment by jwrage** [comment]
@mattharris5 @NathanClinton thanks for your thoughts on this. I can see both sides as well. Could we take the approach of implementing extension points on the elements Matt identified for 3.3 and take under consideration for 3.4 the addition of extension points everywhere?

**Comment by NathanClinton** [comment]
@jwrage I'm cool with that.  @mattharris5 What about xSre?  Seems to me if this is the route xPress is going, SRE should follow step.  I know of two points where we'll need ##other:
- xDisciplineActionType
- xDisciplineIncidentType
- xAttendanceEventType

Can you think of any others?

**Comment by jwrage** [comment]
I will add extension points for the 3 complex requested by @mattharris5 elements today.

**Comment by jwrage** [comment]
4df5a29
