### ISSUE TITLE
Add object descriptions.

### ISSUE THREAD

**Issue by jwrage** [Access4Learning/NADM#25]

**Comment by jwrage** [comment]
@mattharris5 I know you were particularly interested in these. Please review them as added to the XSDs (already committed) and let me know if these read well to you or if you would like changes.

**Comment by mattharris5** [comment]
OK will do.

**Comment by 4pins** [comment]
@mattharris5 once you and @jwrage  are happy with the results, please close.

**Comment by jwrage** [comment]
@mattharris5 for easier reading, these are the descriptions in the annotation/documentation elements of the top level xPress Roster objects:

```
<xqr:xpath-query-result xmlns:xqr="http://www.stylusstudio.com/xpath-query-result">
<!-- Query Result: Element(s) -->
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xStudent is a composite object that provides a view of the most commonly used core data elements for students, and references to important associated objects like contacts. The refId of a xStudent object coincides with the refId of a corresponding student object.</xs:documentation>
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xStaff is a composite object that provides a view of the most commonly used core data elements for teachers and non-teaching staff. The refId of a xStaff object coincides with the refId of a corresponding staff object.</xs:documentation>
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xCourse is a composite object that provides essential information about a course. The refId of a xCourse object coincides with the refId of a corresponding course object.</xs:documentation>
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xSchool is a composite object that provides essential information about a school building or campus. The refId of a xSchool object coincides with the refId of a corresponding school object.</xs:documentation>
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xCalendar is a composite object that provides information about sessions held at a particular school during a given school year. The refId of a xCalendar object coincides with the refId of a corresponding schoolCalendar object.</xs:documentation>
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xRoster is a composite object that provides a consolidated view of information related to a course section or class, including student enrollment and assigned staff. The refId of a xRoster object coincides with the refId of a corresponding section object.</xs:documentation>
<xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xLea is a composite object that provides core information about a Local Educuation Agency (e.g. district, division, intermediate agency). The refId of a xLea object coincides with the refId of a corresponding lea object.</xs:documentation>
</xqr:xpath-query-result>
```

**Comment by ajackl** [comment]
These seem reasonable!

On Tue, May 12, 2015 at 3:41 PM, jwrage notifications@github.com wrote:

> For easier reading, these are the descriptions in the
> annotation/documentation elements of the top level xPress Roster objects:
> 
> <xqr:xpath-query-result xmlns:xqr="http://www.stylusstudio.com/xpath-query-result">
> 
> 
> 
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xStudent is a composite object that provides a view of the most commonly used core data elements for students, and references to important associated objects like contacts. The refId of a xStudent object coincides with the refId of a corresponding student object./xs:documentation
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xStaff is a composite object that provides a view of the most commonly used core data elements for teachers and non-teaching staff. The refId of a xStaff object coincides with the refId of a corresponding staff object./xs:documentation
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xCourse is a composite object that provides essential information about a course. The refId of a xCourse object coincides with the refId of a corresponding course object./xs:documentation
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xSchool is a composite object that provides essential information about a school building or campus. The refId of a xSchool object coincides with the refId of a corresponding school object./xs:documentation
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xCalendar is a composite object that provides information about sessions held at a particular school during a given school year. The refId of a xCalendar object coincides with the refId of a corresponding schoolCalendar object./xs:documentation
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xRoster is a composite object that provides a consolidated view of information related to a course section or class, including student enrollment and assigned staff. The refId of a xRoster object coincides with the refId of a corresponding section object./xs:documentation
> <xs:documentation xmlns:xs="http://www.w3.org/2001/XMLSchema">xLea is a composite object that provides core information about a Local Educuation Agency (e.g. district, division, intermediate agency). The refId of a xLea object coincides with the refId of a corresponding lea object./xs:documentation
> /xqr:xpath-query-result
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SIFAssociation/NADM/issues/25#issuecomment-101396565.

## 

Alex Jackl
ajackl@gmail.com
best number:: 508-395-2836
fax: 617-812-6020

**Comment by mattharris5** [comment]
These are really great. Thanks for updating them. Closing now.
