### ISSUE TITLE
Use of year group

### ISSUE THREAD

**Issue by vinceparedes** [Access4Learning/NADM#27]
The global data model uses the term Year Group to indicate what we in North America call Grade Level. The localization of the global data model allows us to rename elements. 

In xPress Year Group is used instead of Grade Level. Do we want to rename this element?

**Comment by jwrage** [comment]
Thanks for catching this @vinceparedes. Yes, let's please rename to Grade Level. Please let me know if you want me to make the update or if you will.

**Comment by vinceparedes** [comment]
@jwrage , I will make the change.

**Comment by 4pins** [comment]
Still finalizing this change during the final review period.

**Comment by jwrage** [comment]
I actually created a duplicate issue because I had thought this was already done. I also fixed the issue.
