### ISSUE TITLE
Eliminate "Choice"

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#5]
The choice XSD construct is known to cause problems with developer tools.  Replace any occurrences with a sequence with optional children and document.

**Comment by jwrage** [comment]
Which developer tools are affected by this?

**Comment by mattharris5** [comment]
I am curious about that as well... I am by no means experienced at this, but Google searching suggests that `choice` is perfectly valid and compatible. MSDN talks about it plenty. The only spot I could find that suggested some challenge parsing was jaxb doing some weird stuff when generating Java classes from the XSD: http://blog.bdoughan.com/2011/04/xml-schema-to-java-xsd-choice.html

**Comment by jwrage** [comment]
We actually use XJC as part of our POJO generation process so it is actually very relevant :-) Thanks for the details. I'm checking with our dev team to determine if the suggested solution would work for us.

**Comment by jwrage** [comment]
Our dev team does not believe the use of choice will cause a blocker for us. The solution prescribed in the link sent by @mattharris5 will solve the problem. I would recommend that we close this issue as a non-issue and retain CHOICE since it better and more clearly models the intent.

**Comment by 4pins** [comment]
While I'd love to agree (CHOICE hasn't been a problem for me either).  The NATB already discussed and approved removing CHOICE from the NADM 3.3 based on feedback.  I think Jason's question, "Which developer tools are affected by this?" still needs to be answered.

**Comment by jwrage** [comment]
Who are we looking to for an answer? Does @vinceparedes have more specific examples? In general, we should seek fact to back up decisions like this. Also, if we end up going down this path of tailoring the use of perfectly valid XSD then it should be documented as a convention somewhere. If we do not use CHOICE, we'll also need non-normative documentation (which we should probably have anyway) to indicate that xStudent MAY EITHER carry a reference or a full contact (but not both simultaneously). Using CHOICE makes it self-documenting. Using an optional sequence makes it very messy to the casual XSD reader.

**Comment by jwrage** [comment]
Go with optional sequence and make sure it's documented for consistency with the rest of the spec.
