### ISSUE TITLE
Typo on http://specification.sifassociation.org/Implementation/NA/3.3Review/html/indexFiles/ReportObjects.html

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#51]
The text “enegyUsage” is missing the “r” in energy.  The corresponding hyperlink is fine.

http://specification.sifassociation.org/Implementation/NA/3.3Review/html/indexFiles/ReportObjects.html

**Comment by vinceparedes** [comment]
Edited an index file so it did not require a regen.
