### ISSUE TITLE
Wrong type for calendarEventDate

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#55]
xAttendanceEventType -> calendarEventDate is a token when it should be a date.

**Comment by mattharris5** [comment]
Agreed this should be changed per Nathan's suggestion.

**Comment by 4pins** [comment]
@NathanClinton so this isn't in the current pull request?

**Comment by NathanClinton** [comment]
I just created a new pull request for this bug.

**Comment by 4pins** [comment]
@NathanClinton Thanks!
