### ISSUE TITLE
xStudent has no otherAddresses field

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#57]

**Comment by mattharris5** [comment]
@jwrage As we were reviewing today, we realized that this doesn't match the convention. One person on the call mentioned a common use case of physical address vs. mailing address. If this isn't necessary for the xStudent use case, we might add it to xSre in a future version.

**Comment by jwrage** [comment]
This was a “keep it simple” decision and we have anticipated needing to add otherAddresses for xStudent. I would recommend this as an enhancement for 3.4.

**Comment by mattharris5** [comment]
Excellent - makes sense. I've attached this to the 3.4 milestone for now.

**Comment by 4pins** [comment]
@vinceparedes Can you include?

**Comment by 4pins** [comment]
Added!  @vinceparedes Did I use the proper plural form "otherAddresses" for inside an xPress object?
