### ISSUE TITLE
Replace "sexus"

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#6]
"Sexus" needs to only be used as a type and all element definitions should be "sex" or "gender" as appropriate.

**Comment by mattharris5** [comment]
"Sex" and "gender" actually mean different things. Are you saying that both are included in the spec?

**Comment by jwrage** [comment]
The CEDS demographic element is SEX. We should only use SEX, IMO.
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=24811

**Comment by mattharris5** [comment]
Agreed.

**Comment by vinceparedes** [comment]
This has already been done and is reflected in the Master.
