### ISSUE TITLE
Add "Period" information to attendanceEventType

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#64]
It would help to have course and period information attached to attendance event data so we can see which classes a student is missing (skipping, etc.).

**Comment by NathanClinton** [comment]
We are confused how to create "session" information using xRoster and xCourse.  It would be helpful to have Jason's feedback on this issue.

**Comment by mattharris5** [comment]
Looking into this further, I'm not sure how the NADM handles period information at all. I can't find a corresponding object in the Entity Object set. Do we need to create a new way to represent a period? Or is this only relevant to attendance events? If so, we could just add the relevant fields to attendanceEventType. @jwrage, @4pins, and @vinceparedes - any thoughts?

**Comment by mattharris5** [comment]
BTW, recommend we call it `timeTablePeriod` which is the element name used in xMeetingTimeListType/meetingTime.
