### ISSUE TITLE
Need a "description" field for discipline incidents.

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#65]
This will help convey full details about an incident that a code cannot provide.

**Comment by NathanClinton** [comment]
An "incident description" field was found in CEDS.  We will add it to xDisciplineIncidentType.

**Comment by NathanClinton** [comment]
It's actually on xDisciplineActionType.  Matt is going to review if this can be placed into ##other as opposed to creating a new field.

**Comment by mattharris5** [comment]
I think we should add incident description to xDisciplineIncidentType, but we don't need to add it to xDisciplineActionType. We will use the ##other extension point for that.
