### ISSUE TITLE
Do we need to keep track of course schedule information (periods, etc.) for xRoster?

### ISSUE THREAD

**Issue by NathanClinton** [Access4Learning/NADM#66]

**Comment by NathanClinton** [comment]
We reviewed during the SRE meeting and would love to hear Jason's feedback on whether or not to include this in xRoster.

**Comment by 4pins** [comment]
@jwrage Please weigh in.

**Comment by jwrage** [comment]
We would use meetingTimes.meetingTime.timeTablePeriod (and other elements) for this.

**Comment by 4pins** [comment]
@NathanClinton Jason's explanation clears this up for me, you?

**Comment by NathanClinton** [comment]
Sounds good to me!  I'll close the issue.
