### ISSUE TITLE
Mostly Optional

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#7]
Ensure that all the most basic of elements are options (XML Schema default is mandatory).

**Comment by jwrage** [comment]
This was my initial recommendation. See issue regarding marking of mandatory elements that are PII sensitive.

Object,Element,Mandatory,PII considerations

xStudent
@refId,Y,
name.type,,
name.prefix,,
name.givenName,Y,
name.middleName,,
name.familyName,Y,PII considerations
name.suffix,,
otherNames[0].type,,
otherNames[0].prefix,,
otherNames[0].givenName,,
otherNames[0].middleName,,
otherNames[0].familyName,,
otherNames[0].suffix,,
localId,Y,
stateProvinceId
otherIds[0].type
otherIds[0].id
address.type
address.line1
address.line2
address.city
address.stateProvince
address.postalCode
address.countryCode
phoneNumber.type
phoneNumber.primaryIndicator
phoneNumber.number
otherPhoneNumbers[0].type
otherPhoneNumbers[0].primaryIndicator
otherPhoneNumbers[0].number
email.type
email.emailAddress
otherEmails[0].type
otherEmails[0].emailAddress
demographics.birthDate
demographics.sexus
demographics.hispanicLatinoEthnicity
demographics.races[0].race
demographics.usCitizenShipStatus
enrollment.leaRefId
enrollment.schoolRefId
enrollment.homeRoomNumber
enrollment.yearGroup
enrollment.projectedGraduationYear
enrollment.counselorRefId
otherEnrollments[0].leaRefId
otherEnrollments[0].schoolRefId,
otherEnrollments[0].homeRoomNumber,
otherEnrollments[0].yearGroup,
otherEnrollments[0].counselorRefId,
academicSummary.cumulativeWeightedGpa,
academicSummary.termWeightedGpa,
academicSummary.classRank,
studentContacts[],
languages[0].type,
languages[0].code,

xStaff
@refId,Y
name.type,
name.prefix,
name.givenName,Y
name.middleName,,
name.familyName,Y,PII considerations
name.suffix,,
localId,Y,
stateProvinceId,,
otherIds[0].type,,
otherIds[0].id,,
sexus,,
email.type,,
email.emailAddress,,
primaryAssignment.leaRefId,,
primaryAssignment.schoolRefId,,
primaryAssignment.jobFunction,,
otherAssignments[0].leaRefId,,
otherAssignments[0].schoolRefId,,
otherAssignments[0].jobFunction,,

xRoster
@refId,Y
courseRefId,
courseTitle,Y
sectionRefId,
subject,
schoolRefId,Y
schoolSectionId,Y
schoolYear,
sessionCode,
schoolCalendarRefId,
timeTableDay,
classMeetingDays[0],
timeTablePeriod,
roomNumber,
classBeginningTime,,
classEndingTime,,
students[0].refId,Y,
students[0].localId,,
students[0].givenName,Y,
students[0].familyName,Y,PII considerations
primaryStaff.staffPersonReference.refId,Y,
primaryStaff.staffPersonReference.localId,,
primaryStaff.staffPersonReference.givenName,Y,
primaryStaff.staffPersonReference.familyName,Y,
primaryStaff.teacherOfRecord,,
primaryStaff.percentResponsible,,
otherStaff[0].staffPersonReference[0].refId,,
otherStaff[0].staffPersonReference[0].localId,,
otherStaff[0].staffPersonReference[0].givenName,,
otherStaff[0].staffPersonReference[0].familyName,,
otherStaff[0].teacherOfRecord,
otherStaff[0].percentResponsible,

xCourse
@refId,Y
schoolRefId,Y
courseTitle,Y
courseDescription,
schoolCourseId,Y
leaCourseId,
vendorCourseId,
applicableEducationLevels[0],
subject,
scedCourseLevelCode,
scedCourseSubjectAreaCode,
otherIds[0].type,
otherIds[0].id,

xSchool
@refId,Y
leaRefId,Y
localId,
stateProvinceId,
vendorId,
otherIds[0].type,
otherIds[0].id,
schoolName,Y
yearGroups,
address.type,
address.line1,

address.line2,
address.city,
address.stateProvince,
address.postalCode,

address.countryCode,
phoneNumber.type,
phoneNumber.primaryIndicator,
phoneNumber.number,
otherPhoneNumbers[0].type,
otherPhoneNumbers[0].primaryIndicator,
otherPhoneNumbers[0].number,

xContact
@refId,Y
name.type,
name.prefix,
name.givenName,Y
name.middleName,
name.familyName,Y
name.suffix,
localId,
vendorId,
otherIds[0].type,
otherIds[0].id,
address.type,
address.line1,
address.line2,
address.city,
address.stateProvince,
address.postalCode,
address.countryCode,
phoneNumber.type,
phoneNumber.primaryIndicator
phoneNumber.number
otherPhoneNumbers[0].type
otherPhoneNumbers[0].primaryIndicator
otherPhoneNumbers[0].number
email.type
email.emailAddress
otherEmails[0].type
otherEmails[0].emailAddress
sexus
employerType
relationships[0].studentRefId
relationships[0].relationshipCode
relationships[0].emergencyContactIndicator
relationships[0].contactSequence
relationships[0].restrictions
relationships[0].livesWith,
relationships[0].primaryContactIndicator,
relationships[0].financialResponsibilityIndicator,
relationships[0].custodialIndicator,
relationships[0].communicationsIndicator,

xCalendar
@refId,Y
schoolRefId,Y
schoolYear,Y
sessions[0].sessionType,
sessions[0].sessionCode,
sessions[0].sessionDescription,
sessions[0].sessionBeginDate,
sessions[0].sessionEndDate,

xLea
@refId,Y
localId,
stateProvinceId,
vendorId,
ncesId,
leaName,Y
address.type,
address.line1,
address.line2,
address.city,
address.stateProvince,
address.postalCode,
address.countryCode,
phoneNumber.type,
phoneNumber.primaryIndicator,
phoneNumber.number
otherPhoneNumbers[0].type
otherPhoneNumbers[0].primaryIndicator
otherPhoneNumbers[0].number

**Comment by vinceparedes** [comment]
Complete per the spreadsheet from Jason.
