### ISSUE TITLE
Link to http://specification.sifassociation.org/Implementation/NA/3.3Review/ broken

### ISSUE THREAD

**Issue by gsolecki** [Access4Learning/NADM#74]
Link in README.md (https://github.com/SIFAssociation/NADM/blob/master/README.md) pointing to 3.3 review page is broken i.e. this one http://specification.sifassociation.org/Implementation/NA/3.3Review/

**Comment by mattharris5** [comment]
No longer relevant so closing this issue... but we will be more careful during the upcoming review process!
