### ISSUE TITLE
Element version mismatch: SpecialEducationExitReason

### ISSUE THREAD

**Issue by tqwhite** [Access4Learning/NADM#75]
This element has different properties listed in these two views. They should be the same.

https://ceds.ed.gov/cedselementdetails.aspx?termid=3260

https://ceds.ed.gov/element/000260

**Comment by mattharris5** [comment]
@tqwhite: @NathanClinton and I are trying to figure this out... it looks like we are using the longer/newer codeset in the XSD enumerations already so we are just going to update the documentation to refer to only the newer CEDS element.

**Comment by vinceparedes** [comment]
We learned about a year ago (maybe longer) that the CEDS termid changes with each release. Therefore all the termids we have embedded in our XSDs are pointing to CEDS v4, I think. It will matter as CEDS makes more changes. 

The element link is something that CEDS has offered recently to fix the issue. We should be using the https://ceds.ed.gov/element/[element number] format for any new mappings that we do.
