### ISSUE TITLE
Documentation fix for 'marks' object

### ISSUE THREAD

**Issue by rpp9999** [Access4Learning/NADM#88]
A tweak to the description line for the new 'marks' object is in order.

On this page:
http://specification.sifassociation.org/Implementation/NA/3.4/Collections/marks.xhtml

The line under the "Documentation" heading ends:
"...must be used to create a valid MarkValueInfo."

Looks like a copy/paste holdover from 2.7M, should maybe say 'mark' instead of 'MarkValueInfo'.

**Comment by vinceparedes** [comment]
Agreed. I will make the change. 

## Thanks. 

Vince Paredes
vinceparedes@gmail.com
512-785-7116

**Comment by vinceparedes** [comment]
change pushed to branch.
