### ISSUE TITLE
Mandatory elements and PII

### ISSUE THREAD

**Issue by jwrage** [Access4Learning/NADM#9]
Should sensitive identifying elements that are subject to PII rules be flagged as mandatory in the XSD? familyName is the best example.

**Comment by mattharris5** [comment]
If they're mandatory, and sensitive, and a provider wants to strip out the sensitive element, then isn't that an argument to make them _optional_, actually?

**Comment by jwrage** [comment]
Absolutely. Just want to check with the larger group. I had not thought about familyName being an issue prior to very recently.

**Comment by mattharris5** [comment]
This is one of the reasons SRE went with the "everything optional" strategy (literally only `refid` was required). I can imagine a use-case where someone provides student data without names at all (e.g., for research purposes).

**Comment by jwrage** [comment]
My original thinking more closely matched SIF 2 patterns. I'm coming around to the idea of full optionality save for refIds.

**Comment by jwrage** [comment]
I propose we have xPress follow the SRE pattern of only requiring refIds and eliminate all other mandatory elements.

**Comment by jwrage** [comment]
XSDs updated to make MOST items optional save for Keys. Followed established conventions in substructures to require an element instance of the parent structure is present.
