### ISSUE TITLE
xStudent/race includes a redundant parent element

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#90]
I think we discussed this before the last release, however it jumped out at me.

Why:
/xStudents​/xStudent​/demographics​/races​**/race​/race**

**Comment by mattharris5** [comment]
I _think_ this is an artifact of the old coded element structure that was made obsolete with xPress now that we use enumerated values, where previously we had `races` as the list container, and then `race` as the `RaceType` object, and the `race` and `raceCode` and other such things as the lowest level elements. I think it simply was a mistake in the xPress publication, but now it would be a breaking change to fix.

**Comment by 4pins** [comment]
@mattharris5 @jwrage The RICOne sandbox still shows this as nested, so I think we keep it.

**Comment by mattharris5** [comment]
Agreed on the Aug 3 NATB call that we won't fix this for now.
