### ISSUE TITLE
EmploymentStatus in employmentRecord​

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#93]
Describes if staff is on paid or unpaid leave or active or could this info be added to the Active element?

MA uses: 
Employed
Terminated
Paid Leave
Unpaid Leave

**Comment by mattharris5** [comment]
Recommend aligning to [CEDS Element 000347 - `EmploymentStatus`](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=28124)

For tracking types of Leave, you could also use [`LeaveEventType`](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=28139)

**Comment by 4pins** [comment]
@vinceparedes So this seems like a fine place for this kind of element, if so lets use a plug-able code set structure.

**Comment by vinceparedes** [comment]
Added the Employment Status element. Referenced the CEDS element Employment Status but also widened the scope to include MA codeset values in the documentation.

**Comment by 4pins** [comment]
Why is this not of type gCodedElementType?

**Comment by vinceparedes** [comment]
I did not change the existing element type. I have only been doing additions so far not changes to existing elements. 

However, I have no objection to doing that and will do so.

**Comment by vinceparedes** [comment]
Changed to gCodedElementType
