### ISSUE TITLE
ReasonForExit in employmentRecord​

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#94]
MA:
Reason for exit.  Sample values available on request

**Comment by 4pins** [comment]
01 = Personal 
02 = Layoff
03 = Contract Not Continued or Renewed
04 = District Discharge
05 = Death
06 = Retirement
07 = Reason Unknown/Other
08 = Other employment in Pre K–12 public education 
09 = Other employment in education
10 = Other employment outside education
11 = Dismissed as a result of an unsatisfactory summative rating on evaluation

**Comment by mattharris5** [comment]
Recommend aligning this to CEDS Element 000620 - `EmploymentSeparationReason`
https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=28136

@4pins Are those codes that you provided from MA or some other source?

**Comment by 4pins** [comment]
@mattharris5 MA

**Comment by 4pins** [comment]
@vinceparedes Sounds like we need the element with a plug-able code set structure.

@ajackl @rpp9999 We may need to consider a Code Sets Project Team

**Comment by leslie8751** [comment]
Wyoming uses a different set of codes for the reason for separation.   Would consider aligning.

**Comment by vinceparedes** [comment]
Added element: separationReason. Also referenced the CEDS element Employment Separation Reason in the documentation.
