### ISSUE TITLE
StateCourseCode in course?

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#96]
MA: How should the StateCourseCode be conveyed in SIF 3.

Probably:
/courses​/course​/courseCode​/code

**Comment by 4pins** [comment]
DistrictCourseCode too!

**Comment by vinceparedes** [comment]
Yes, courseCode. SCED codes and any other codes (such as local course Id) can be put in otherCodeList.

**Comment by mattharris5** [comment]
I would recommend that `course` inherit from `xCourse` which already provides for this in the `otherIds` element.

**Comment by mattharris5** [comment]
Also, aren't we getting rid of the "[ElementName]List" paradigm in favor of just the plural form, like we do in all of the xPress objects?

**Comment by 4pins** [comment]
@mattharris5 No, my understanding is the xPress objects (for which no one may be integrating a enterprise solution) use the plural where the enterprise objects use "List."

**Comment by vinceparedes** [comment]
Again, no change required here. A note should be sent to MA detailing how to convey state, district, and SCED course code in the otherIds list.
