### ISSUE TITLE
InstructionalLevel/Code in course?

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#97]
MA needs the actual code element brought forward into SIF 3.

**Comment by 4pins** [comment]
NCES0437 Code - See Instructional Level Map

**Comment by vinceparedes** [comment]
Hmm, good point. And it should be a list as well, right? Courses can apply to multiple levels.

**Comment by 4pins** [comment]
Yes, I agree it should be a list!

**Comment by vinceparedes** [comment]
Looking more closely at the element in 2.7: In 2.7 it is not a grade level code as you were probably thinking. It is a code like honors, college-level, remedial and meant to be a single element and not a list. 

The element is already there as instructional level. It is typed as gInstructionalLevel type. We could make a coded element type instead. That would simplify things. 

Do we still want to make it a list?

**Comment by vinceparedes** [comment]
@4pins , what do you think?

**Comment by chelmsfordking** [comment]
A list would not really work for MA.  If a course does have different levels, that would probably be better located in a section definition.  With a list, we would have no way of knowing which section was at which level or which had multi-levels.  Come to think of it, a level override would be nice in section?

**Comment by vinceparedes** [comment]
Moved intstructionalLevel from global to courseType. Made courseType a coded element type and referenced the CEDS element.
